name: ${project.name}
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: DarkBlade12
softdepend: [Vault, Factions, Multiverse-Core, Multiworld, PlotMe, MyWorlds]
api-version: 1.13

main: com.darkblade12.simplealias.SimpleAlias

commands:
  alias:
    usage: /<command> help
    aliases: [simplealias, salias, sa]