# Copyright DarkBlade12 - All rights reserved.
# DarkBlade12 is the developer and respective owner of this plugin.

# This section contains general plugin settings
General_Settings:

 # Determines whether full error logs are shown in the console
 # This is helpful when you have problems you can't solve by yourself and want to show an exception to the developer
 Debug_Enabled: false

 # Determines whether the uncommented or the commented template will be used and copied
 # This setting is for more advanced users who know about all the options and want a clearer template
 # Please make sure to delete your old 'template.yml' file after changing this setting (reloading the server/plugin or creating an alias will create a new template file)
 Uncommented_Template: false
 
 # Determines whether the converter for old alias configs is enabled
 Converter_Enabled: false
 
 # The section below contains commands which will be disabled by SimpleAlias
 # This is useful if you want that a certain alias is used instead of the original command
 # You can add them by making a section like this: '<command>: <message>'
 # The examples below are disabled, in order to enable them simply remove the '#'
 # Color codes starting with '&' and unicode symbols will be translated
 Disabled_Commands:
  
  # plugins: 'Unknown Command. Type "/help" for help.'
  # time: 'Unknown Command. Type "/help" for help.'
  
 # The section below contains abbreviated names for alias settings
 # You can add them by making a section like this: '<abbreviation>: <setting_name/setting_path>
 Setting_Abbreviations:
 
  desc: "General_Settings.Description"
  exac: "General_Settings.Executable_As_Console"
  enwo: "General_Settings.Enabled_Worlds"
  exor: "General_Settings.Execution_Order"
  uscen: "General_Settings.Usage_Check.Enabled"
  uscminp: "General_Settings.Usage_Check.Min_Params"
  uscmaxp: "General_Settings.Usage_Check.Max_Params"
  uscme: "General_Settings.Usage_Check.Message"
  permen: "General_Settings.Permission.Enabled"
  permno: "General_Settings.Permission.Node"
  permgr: "General_Settings.Permission.Groups"
  permme: "General_Settings.Permission.Message"
  delen: "General_Settings.Delay.Enabled"
  delcom: "General_Settings.Delay.Cancel_On_Move"
  deldur: "General_Settings.Delay.Duration"
  delme: "General_Settings.Delay.Message"
  delcme: "General_Settings.Delay.Cancel_Message"
  coolen: "General_Settings.Cooldown.Enabled"
  cooldur: "General_Settings.Cooldown.Duration"
  coolme: "General_Settings.Cooldown.Message"
  costen: "General_Settings.Cost.Enabled"
  costam: "General_Settings.Cost.Amount"
  costme: "General_Settings.Cost.Message"
  logen: "General_Settings.Logging.Enabled"
  logme: "General_Settings.Logging.Message"
  
 # The section below contains abbreviated names for action settings
 # You can add them by making a section like this: '<abbreviation>: <setting_name/setting_path>
 Action_Setting_Abbreviations:
  
  enwo: "Enabled_Worlds"
  enpermno: "Enabled_Permission_Nodes"
  enpermgr: "Enabled_Permission_Groups"
  enpa: "Enabled_Params"
  prio: "Priority"
  trcc: "Translate_Color_Codes"
  cmd: "Command"
  exec: "Executor"
  gperm: "Grant_Permission"
  txt: "Text"
  bcast: "Broadcast"