name: SimpleAlias
version: 1.6.0
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12
description: SimpleAlias allows you to create and manage aliases easily
softdepend: [Vault, Factions, Multiverse-Core, Multiworld, PlotMe, MyWorlds]

main: com.darkblade12.simplealias.SimpleAlias

commands:
  alias:
    usage: /<command> help
    aliases: [simplealias, salias, sa]