name: SimpleAlias
version: 1.5.0
author: DarkBlade12
website: http://dev.bukkit.org/profiles/DarkBladee12
softdepend: [Vault, Factions]

main: com.darkblade12.simplealias.SimpleAlias

commands:
  sa:
    usage: /<command> help
    aliases: [simplealias, salias]